// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC0XYLfFrQIseEMt2baWSIcvWObq7HHto',
    appId: '1:472403004735:web:d4bf889c13e1225354178a',
    messagingSenderId: '472403004735',
    projectId: 'homewallet-prod',
    authDomain: 'homewallet-prod.firebaseapp.com',
    storageBucket: 'homewallet-prod.firebasestorage.app',
    measurementId: 'G-M5372C7RJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUehGhse5KBIDHRqivZU5ewyUeprSce2c',
    appId: '1:472403004735:android:31279f29e54d70cc54178a',
    messagingSenderId: '472403004735',
    projectId: 'homewallet-prod',
    storageBucket: 'homewallet-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj3hQCIyP1qoJcGePwtIctzgtLI7xXaxY',
    appId: '1:472403004735:ios:647308d74bcac89f54178a',
    messagingSenderId: '472403004735',
    projectId: 'homewallet-prod',
    storageBucket: 'homewallet-prod.firebasestorage.app',
    iosClientId:
        '472403004735-jdah9mo075lq7bnugp7unb8p3hfh4d27.apps.googleusercontent.com',
    iosBundleId: 'com.homewallet.app',
  );
}
